/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Bookcase(props) {
	const { nodes, materials } = useGLTF("models/bookcase.glb");
	const ref = useRef();
	return (
		<group {...props} dispose={null} ref={ref}>
			<group
				position={[0.004, 0, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_1.geometry}
					material={materials.Wood1}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_2.geometry}
					material={materials.Wood2}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_3.geometry}
					material={materials.DarkWood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_4.geometry}
					material={materials.Cover1}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_5.geometry}
					material={materials.Pages}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_6.geometry}
					material={materials.Cover6}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_7.geometry}
					material={materials.Cover2}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_8.geometry}
					material={materials.Cover3}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_9.geometry}
					material={materials.Cover4}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_Single_10.geometry}
					material={materials.Cover5}
				/>
			</group>
			<group
				position={[0.775, 0.588, 0.299]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_RightDoor_1.geometry}
					material={materials.DarkWood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_RightDoor_2.geometry}
					material={materials.Metal}
				/>
			</group>
			<group
				position={[-0.77, 0.588, 0.299]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_LeftDoor_1.geometry}
					material={materials.DarkWood}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.BookCase_LeftDoor_2.geometry}
					material={materials.Metal}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("models/bookcase.glb");
