/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Cat(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("models/Cat.glb");
	const { actions } = useAnimations(animations, group);
	console.log("Actions: ", actions);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='AnimalArmature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<primitive object={nodes.All} />
						<primitive object={nodes.Root} />
					</group>
					<skinnedMesh
						name='Cat'
						geometry={nodes.Cat.geometry}
						material={materials.AtlasMaterial}
						skeleton={nodes.Cat.skeleton}
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}
					/>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/Cat.glb");
