/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("models/Figgy.glb");
	const ref = useRef();
	return (
		<group {...props} dispose={null}>
			<mesh
				ref={ref}
				castShadow
				receiveShadow
				geometry={nodes.FiddleleafFigPottedPlant_mesh.geometry}
				material={materials.FiddleleafFigPottedPlant_mat}
			/>
		</group>
	);
}

useGLTF.preload("models/Figgy.glb");
