/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const ACTION_MAP = {
	attack: "Fish_Armature|Attack",
	death: "Fish_Armature|Death",
	outOfWater: "Fish_Armature|Out_Of_Water",
	swimmingFast: "Fish_Armature|Swimming_Fast",
	swimmingImpulse: "Fish_Armature|Swimming_Impulse",
	swimmingNormal: "Fish_Armature|Swimming_Normal",
};

export default function MandarinFish(props) {
	const group = useRef();
	const { nodes, materials, animations } = useGLTF("models/MandarinFish.glb");
	const { actions } = useAnimations(animations, group);

	useEffect(() => {
		const swimmingAction = actions[ACTION_MAP.swimmingNormal];
		if (swimmingAction) {
			swimmingAction.play();
		}
	}, [actions]);
	return (
		<group ref={group} {...props} dispose={null}>
			<group name='Root_Scene'>
				<group name='RootNode'>
					<group
						name='Fish_Armature'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<primitive object={nodes.Main1} />
					</group>
					<group
						name='MandarinFish'
						rotation={[-Math.PI / 2, 0, 0]}
						scale={100}>
						<skinnedMesh
							name='MandarinFish_1'
							geometry={nodes.MandarinFish_1.geometry}
							material={materials.MandarinFish_Main}
							skeleton={nodes.MandarinFish_1.skeleton}
						/>
						<skinnedMesh
							name='MandarinFish_2'
							geometry={nodes.MandarinFish_2.geometry}
							material={materials.MandarinFish_Light}
							skeleton={nodes.MandarinFish_2.skeleton}
						/>
						<skinnedMesh
							name='MandarinFish_3'
							geometry={nodes.MandarinFish_3.geometry}
							material={materials.MandarinFish_Dark}
							skeleton={nodes.MandarinFish_3.skeleton}
						/>
						<skinnedMesh
							name='MandarinFish_4'
							geometry={nodes.MandarinFish_4.geometry}
							material={materials.Eyes}
							skeleton={nodes.MandarinFish_4.skeleton}
						/>
					</group>
				</group>
			</group>
		</group>
	);
}

useGLTF.preload("models/MandarinFish.glb");
