/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/HousePlant.glb");
	const ref = useRef();
	return (
		<group {...props} dispose={null} ref={ref}>
			<group
				position={[-0.519, 0.102, -0.073]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plant2_1.geometry}
					material={materials["Plant.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plant2_2.geometry}
					material={materials["Plant.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plant2_3.geometry}
					material={materials["Plant.003"]}
				/>
			</group>
		</group>
	);
}

useGLTF.preload("/HousePlant.glb");
