/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Shelf(props) {
	const { nodes, materials } = useGLTF("models/Shelf.glb");
	const ref = useRef();
	return (
		<group {...props} dispose={null} ref={ref}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Shelf_01_Plane005.geometry}
				material={materials.FFCC88}
			/>
		</group>
	);
}

useGLTF.preload("models/Shelf.glb");
