/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
	const { nodes, materials } = useGLTF("/NautilusShell.glb");
	const ref = useRef();
	return (
		<group {...props} dispose={null} ref={ref}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.nautilus_shell.geometry}
				material={materials.None}
			/>
		</group>
	);
}

useGLTF.preload("/NautilusShell.glb");
