/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function StarFish(props) {
	const { nodes, materials } = useGLTF("models/Starfish.glb");
	const ref = useRef();
	return (
		<group {...props} ref={ref} dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes["Node-Mesh"].geometry}
				material={materials.lambert3SG}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes["Node-Mesh_1"].geometry}
				material={materials.lambert2SG}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes["Node-Mesh_2"].geometry}
				material={materials.lambert4SG}
			/>
		</group>
	);
}

useGLTF.preload("models/Starfish.glb");
